server:
  port: 8081

spring:
  application:
    name: RIDE-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/tripDB
    username: root
    password: pawan

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka