server:
  port: 9083

spring:
  application:
    name: RIDE-SERVICE

  datasource:
    url: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/tripDB2
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect


# Swagger Configurations
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true

# Ethereum configuration
ethereum:
  contract-address: 0x2D775eA6e0163f701F5481a6C0621EDD8841E4A1
  blockchain-key: 0x70d2e3a11fe294288df4c1ce72015054d16c23268a442004be044edbb118331b