apiVersion: v1
kind: Secret
metadata:
  name: authserver-secret
  namespace: default # Adjust namespace as needed
type: Opaque
data:
  FIREBASE_DATABASE: <base64-encoded-firebase-database-url>
  DOMAIN: <base64-encoded-domain>
