server:
  port: 9099

spring:
  application:
    name: RIDE-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/tripDB
    username: root
    password: pawan

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
