server:
  port: 9099

spring:
  application:
    name: RIDE-SERVICE

  datasource:
    url: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/searchridedb
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
