export default {
  // Services
  MAIL_SERVICE: "MAIL_SERVICE",
  MAIL_SERVICE_NAME: "MAIL_SERVICE_V1",

  RIDE_SERVICE: "RIDE-SERVICE",
  RIDE_SERVICE_NAME: "RIDE-SERVICE_V1",

  AUTH_SERVICE: "AUTH-SERVER",
  AUTH_SERVICE_NAME: "AUTH-SERVER_V1",
};
